### PR TITLE
Add some description

### PR DESCRIPTION
**Pull request by abadger**
##### ISSUE TYPE
- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by gundalow** [comment]
bot_status

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): False
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
bot_status

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: core
maintainers: 

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
bot_status

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: core
maintainers: 

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
bot_status

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: core
maintainers: 

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
Not getting maintainers set

**Comment by abadger** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: core
maintainers: 

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by abadger** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: core
maintainers: 

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: core
maintainers: 

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: core
maintainers: 

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: core
maintainers: 

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: core
maintainers: 

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
cc @bcoca
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: community
maintainers: bcoca

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: community
maintainers: bcoca

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): False
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: community
maintainers: bcoca

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: community
maintainers: bcoca

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: community
maintainers: bcoca

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: community
maintainers: bcoca

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
<details><summary><b>Components</b></summary>

[README.md](https://github.com/ansible/ansible/blob/devel/README.md)
support: core
maintainers: 

[plugins/modules/jabber.py](https://github.com/ansible/ansible/blob/devel/plugins/modules/jabber.py)
support: community
maintainers: bcoca

</details>

<details><summary><b>Metadata</b></summary>

**waiting_on**: abadger
changes_requested_by: null
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): True
[needs_revision](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_revision): True
[needs_rebase](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_rebase): False
[merge_commits](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-merge_commit): []
too many files or commits: False
mergeable_state: unstable
shippable_status: failure
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other: 
automerge: automerge shipit test failed
</details>

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Pull request closed without merging**
